version: '3'
volumes:
  # todos containers que precisam de persistencia de dados devem ter um vomule configurado
  web:
  database:
  web-api:
networks:
  # todas redes precisam ser declaradas
  alerts:
  database:
  dataprocessing:
  iot:
  web:
    # driver:
services:
  web:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html
      # Configuração do proxy reverso
      - ./web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      # Estou usando o 8080 temporáriamente, pois meu IIS está na porta 80
      - 8080:80
    networks:
      - web
    depends_on:
      - web-api
  database:
    image: postgres:12.0-alpine
    volumes:
      #Volume dos dados
      - database:/var/lib/postgres/data
      #Scripts
      - ./data-base/scripts:/docker-entrypoint-initdb.d
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=pK9mE9csuUpFoezBlXh3
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - database
  web-api:
    image: python:3.6
    volumes:
      #Aplicação Web
      - ./apis/web-api:/web-api
    working_dir: /web-api
    command: bash ./web-api.sh
    networks:
      - database
      - web
    depends_on:
      - database
    environment:
      #Variáveis de ambiente são obrigatórias para dados sensíveis
      - DB_HOST=database
      - DB_USER=smartcare
      - DB_PASS=820cfb9bb413498ae07941b7bac0582b
      - DB_NAME=smartcare_db
    
    
      